### ISSUE TITLE
No more logging in.

### ISSUE THREAD

**Issue by anna-averianova** [SEP007/lmvc-patat#44]
This is not alright @tdeekens ! No one can do anything!

``` php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Method or property does not exists' in /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/troba/lib/troba/Model/Getters.php:31
Stack trace:
#0 /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/lmvc-modules/lib/Scandio/lmvc/modules/security/SecureController.php(18): Scandio\lmvc\modules\security\handlers\database\models\Users->__call('isAuthenticated', Array)
#1 /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/lmvc-modules/lib/Scandio/lmvc/modules/security/SecureController.php(18): Scandio\lmvc\modules\security\handlers\database\models\Users->isAuthenticated()
#2 [internal function]: Scandio\lmvc\modules\security\SecureController::preProcess('')
#3 /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/lmvc/lib/Scandio/lmvc/LVC.php(427): call_user_func_array('controllers\Men...', Array)
#4 /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/lmvc/lib/Scandio/lmvc/LVC.php(256): Scandio\lmvc\LVC->run()
#5 /Applications/MAMP/htdocs/lmvc-patat/index.php(12): in /Applications/MAMP/htdocs/lmvc-patat/composer/scandio/troba/lib/troba/Model/Getters.php on line 31
```

**Comment by tdeekens** [comment]
Wowsi, wowsi.
Originated from a merge with `lmvc-module`'s origin. No names to be called...

Fixed now...
